# Generated by Django 5.2.1 on 2025-06-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute", "value"), name="unique_attribute_value"
            ),
        ),
    ]
