# Generated by Django 5.2.1 on 2025-07-03 11:57

import Product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_attributevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=150,
                unique=True,
                validators=[Product.validators.validate_slug],
                verbose_name="Attribute Slug",
            ),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=150,
                unique=True,
                validators=[Product.validators.validate_slug],
                verbose_name="Attribute Value Slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                unique=True,
                validators=[Product.validators.validate_slug],
                verbose_name="Category Slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=150,
                unique=True,
                validators=[Product.validators.validate_slug],
                verbose_name="Product Slug",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=120,
                unique=True,
                validators=[Product.validators.validate_slug],
                verbose_name="Product Type Slug",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=60,
                unique=True,
                validators=[Product.validators.validate_slug],
            ),
        ),
    ]
